<a href="https://colab.research.google.com/github/Sankarsh-Sunku/Implementation-Of-DL-in-Pytorch/blob/main/ANN/ANN_num_Parameters.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[0.1718, 0.3969],
        [0.4615, 0.2472]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.1383, -0.4396], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.1871, -0.1694],
        [-0.2258,  0.4404]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.0050,  0.5409], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.4148,  0.0994],
        [-0.0265, -0.0168],
        [-0.3621, -0.0458]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([ 0.5313, -0.5531, -0.0809], requires_grad=True))
 


In [4]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [6]:
# just the parameters
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[-0.0901, -0.2126],
        [ 0.4673, -0.5986],
        [-0.2724,  0.1243],
        [-0.3050,  0.0381]], requires_grad=True)
 
Parameter containing:
tensor([ 0.4403, -0.6690, -0.6978, -0.2262], requires_grad=True)
 
Parameter containing:
tensor([[ 0.4115,  0.0530, -0.1490,  0.2904],
        [-0.0731,  0.0756,  0.0400, -0.2141],
        [-0.1635,  0.1332, -0.4989, -0.3412]], requires_grad=True)
 
Parameter containing:
tensor([-0.4664,  0.3418, -0.1733], requires_grad=True)
 


In [7]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [8]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [9]:
# A nice simple way to print out the model info.
from torchsummary import summary
summary(widenet,(1,2))


----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
